### PR TITLE
Donate Page

### PR DESCRIPTION
**Pull request by CMacxC**

### CODE REVIEW

**Review by bairon-cano — CHANGES_REQUESTED** [review]
The spacing is set too high, and the content looks too far apart. There is also a bug in the accordion component, but that one is fixed by me. Change the spacing so that the content looks more appropriate, you can see the page I made of volunteer-form.

**Comment by pybalt** [comment]
Also, `src/data/ong.ts` seems to have problems with the latest version on the main. That's on me. I'll change and merge it once it pass the pipelines

**Comment by pybalt** [comment]
@bairon-cano what should we do?

**Comment by bairon-cano** [comment]
> @bairon-cano what should we do?

At the moment I'm doing the volunteer page, when I finish that one, I'll do this one.

**Pull request closed without merging**
